name: Xformers Compiler

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: xformers-build
  cancel-in-progress: true

env:
  # you need at least cuda 5.0 for some of the stuff compiled here.
  TORCH_CUDA_ARCH_LIST: "5.0+PTX 6.0 6.1 7.0 7.5 8.0 8.6"
  FORCE_CUDA: 1
  MAX_JOBS: 1 # will crash otherwise
  DISTUTILS_USE_SDK: 1 # otherwise distutils will complain on windows about multiple versions of msvc

jobs:
  linux-compiler:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - name: go to xformers
        uses: actions/checkout@v3
        with:
          repository: facebookresearch/xformers
          submodules: recursive
          ref: main
      - run: |
          sudo apt-get update
      - name: install cuda
        uses: Jimver/cuda-toolkit@v0.2.8
        with:
          cuda: '11.6.0'
          linux-local-args: '["--toolkit"]'
      - name: Build
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: |
          pip install wheel setuptools twine -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu116
          pip install ninja
          python setup.py bdist_wheel -d dist/ -k --plat-name manylinux2014_x86_64
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: abc
          path: ./dist/*.whl
