name: Xformers Compiler

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
  
env:
  # you need at least cuda 5.0 for some of the stuff compiled here.
  TORCH_CUDA_ARCH_LIST: "7.5"
  FORCE_CUDA: 1
  MAX_JOBS: 1 # will crash otherwise
  DISTUTILS_USE_SDK: 1 # otherwise distutils will complain on windows about multiple versions of msvc
  XFORMERS_PACKAGE_FROM: "wheel-${{ github.ref_name }}"

jobs:
  linux-compiler:
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.10"
          - "3.9"
        config:
          - cuda_version: "11.8.0"
            pip_index: https://download.pytorch.org/whl/cu118
            cuda_run_file: https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_520.61.05_linux.run
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux2014_x86_64
    timeout-minutes: 360
    defaults:
      run:
        shell: bash
    steps:
      # - uses: actions/checkout@v3
      - name: go to xformers
        uses: actions/checkout@v3
        with:
          repository: facebookresearch/xformers
          submodules: recursive
          ref: main
          path: "."
          fetch-depth: 0
      - name: install cuda
        run: >
          yum install wget git prename -y &&
          wget -q "${{ matrix.config.cuda_run_file }}" -O cuda.run &&
          sh ./cuda.run --silent --toolkit &&
          rm ./cuda.run
      - name: Define version
        run: |
          set -Eeuo pipefail
          git config --global --add safe.directory "*"
          python${{matrix.python}} -m pip install packaging
          version=`python${{matrix.python}} packaging/compute_wheel_version.py`
          echo "BUILD_VERSION=$version" >> ${GITHUB_ENV}
          cat ${GITHUB_ENV}
      - name: get datetime vars
        id: datetime-vars
        run: |
          echo "datetime=$(/bin/date -u +"%Y/%m/%d/%H%M")" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          python${{matrix.python}} -m venv --upgrade-deps venv
          source venv/bin/activate
          python${{matrix.python}} -m pip install wheel ninja
          python${{matrix.python}} -m pip install --pre torch torchvision torchaudio triton --index-url ${{ matrix.config.pip_index }}
          python${{matrix.python}} -m pip install -r requirements.txt
          python${{matrix.python}} setup.py bdist_wheel -d dist/ -k --plat-name manylinux2014_x86_64
      - name: get vars
        id: get-vars
        run: |
          echo "releasebody=$(pip freeze | grep torch)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.5.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/*.whl
          tag: xformers-cuda${{matrix.config.cuda_version}}-${{steps.datetime-vars.outputs.datetime}}
          body: ${{ steps.get-vars.outputs.releasebody }}
          file_glob: true
          overwrite: true
          prerelease: true
