name: Xformers Compiler

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: xformers-build
  cancel-in-progress: true

jobs:
  linux-compiler:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - name: go to xformers
        uses: actions/checkout@v3
        with:
          repository: facebookresearch/xformers
          submodules: recursive
          ref: main
      - run: |
          sudo apt-get update
      - name: Build
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1' 
      - run: |
          pip install torch torchvision triton --extra-index-url https://download.pytorch.org/whl/cu116
          pip install -r requirements.txt
          pip install wheel
          pip install ninja
          python setup.py build
          python setup.py bdist_wheel
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: abc
          path: ./dist/*.whl
          # path: ./object-creator.zip